### ISSUE TITLE
someone modded my app.

### ISSUE THREAD

**Issue by SystemRestored** [DimaKoz/stunning-signature#3]
Some one modded my app and copied my CERT.RSA from original app, and included in his META-INF and renamed it to  com_android_support_support-core-ui.XSA ,

The cert verification results original signature. how is it possible?

**Comment by SystemRestored** [comment]
This code can easily be hacked. In a hex editor anyone can load the .so file and edit the method file to change which file will be selected for scanning of original key. Then they make modded app signed with their signature , unzip the apk, put original rsa of original app  in the apk.

**Comment by DimaKoz** [comment]
Sure, reverse-engineers always win, it is obvious. You shouldn't use this example without any changes in your app.
