### ISSUE TITLE
there's a simpler way to do it

### ISSUE THREAD

**Issue by Haoxiqiang** [DimaKoz/stunning-signature#8]
I suggest get PM from native code can do the samething.
replace
getPackageInfo(package, 0)[0]
with
env->GetMethodID(cz_pm,"getPackageInfo","(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;"
more ...

**Comment by emileb** [comment]
I think the point is to avoid having any Java in the chain as it can be easily intercepted.

**Comment by Pecana** [comment]
> I suggest get PM from native code can do the samething.
> replace
> getPackageInfo(package, 0)[0]
> with
> env->GetMethodID(cz_pm,"getPackageInfo","(Ljava/lang/String;I)Landroid/content/pm/PackageInfo;"
> more ...

This is not secure, it can be easly hooked

**Comment by Haoxiqiang** [comment]
yeah,in fact, they are no different.
I don't know how to avoid the hook.
